# line to insert in database for table 'gps' has the following structure : gps_id(AI) - gps_longitude - gps latitude - gps_address - gps_zip (44000) - gps_city(Nantes)

INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.212100,-1.548230,"Rue berthault",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square du lait de mai","Inauguré en juin 2002, ce jardin public de taille humaine, est situé entre la rue péhant et la rue berthault.abritée sous une pergola, une fontaine de mosaïque réalisée par delphine deltombe.a l'opposé, une petite maison de brique et de bois construit",1,"parks",1);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.212000,-1.557750,"Place de la petite hollande",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square jean-batiste daviais","Ou square de la petite hollandeconçu par etienne coutant, cet espace situé en proue de l'île feydeau, a été aménagé après les comblements de loire. un bassin et quelques plantations viennent agrémenter le site.dans les années 1930, les comblements d",2,"parks",2);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.219800,-1.542920,"Place charles leroux",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Jardin des plantes","Cest en 1807 que débute la création du jardin des plantes. caractéristique des jardins paysagers du siècle dernier, il présente un modelé souple avec de nombreuses cascades et pièces deau ainsi quune décoration florale abondante maintenant la tradition",3,"parks",3);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.217500,-1.554430,"Place de l'hotel de ville",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square amiral halgand","Le square de la mairie date de la reconstruction d'après-guerre, quelques jeux et la statue du général leclerc sont les principaux ornements.",4,"parks",4);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.214400,-1.567660,"Place de l'edit de nantes",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square de l'edit de nantes","Réaménagé en 1996, ce petit square de quartier offre à la fois des jeux pour enfants et un espace jardiné pour les riverains.",5,"parks",5);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.218000,-1.550360,"Cours st pierre - impasse st laurent - impasse de la psalette",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square psalette","",6,"parks",6);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.216200,-1.563420,"Place newton",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square pascal lebee","Réaménagé en 1997, ce square a laissé la place à un aménagement ouvert favorisant les liaisons piétonnes dans le quartier.a noter la plantation de pyrus 'bradford'",7,"parks",7);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.216300,-1.549160,"Rue des etats",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Douves du château des ducs","",8,"parks",8);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.215000,-1.544680,"Quai ferdinand favre",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square jean heurtin","Ce petit square situé dans la zac de la madeleine champs de mars et ouvert en 1998 est planté de nombreux camellias afin de commémorer jean heurtin, pépiniériste nantais, célèbre obtenteur de la fin du xix ème.",9,"parks",9);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.212000,-1.563080,"Rue des cadeniers",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Cours cambrone","Le cours planté de très beau magnolia grandiflora, orné de boulingrins et de massifs fleuris ainsi que de la statue du général cambronne assure la liaison entre la place graslin et les quais de la fosse.",10,"parks",10);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.212900,-1.564890,"Place de la monnaie",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square louis bureau","Espace vert d'accès au muséum d'histoire naturelle, ce square orné d'un boulingrin et de beaux arbres devrait évoluer progressivement en salle d'animation extérieure pour le muséum.",11,"parks",11);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.212300,-1.568500,"Rue desire colombe",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc say","Ce petit parc actuellement sous utilisé du fait de son enclavement devrait pouvoir bénéficier prochainement d'une ouverture sur les espaces publics de la zac située à proximité.",12,"parks",12);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.214200,-1.550370,"Cours commandant estienne d'orves",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square elisa mercoeur","Square de  l'après-guerre, il a été conçu comme un jardin pour les enfants du centre ville. dans ce secteur en pleine mutation, il sera prochainement transformé et rendu plus accessible. la fontaine de verre créée par fonteneau évoque un manège enfantin.",13,"parks",13);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.217900,-1.563470,"Rue faustin helie",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square faustin hélie","Espace vert d'accompagnement de l'ancien palais de justice, ce square bien planté offre des espaces de repos ombrés aux gens du quartier.",14,"parks",14);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.211100,-1.562820,"Rue d'ancin",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square gabriel chéreau","Réaménagé en 1995, ce square de quartier n'est accessible que par l'intérieur de la médiathèque, en 2011, à la demande des habitants du quartier, une partie du square a été aménagée en jardin partagé : le papotager.",15,"parks",15);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.246300,-1.516080,"Rue de la haluchère - rue emile gadeceau",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square des maraiches","'Le square ''le jardin des maraîches'' a été créé en 2003 en concertation avec les habitants autour du thème et fil conducteur du maraîchage, pour rappeler l'ancienne activité du site.le mot maraîche était utilisé autrefois populairement par les gens du qu'",16,"parks",16);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.226800,-1.522550,"Place gabriel trarieux",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc de broussais","Il s'agit du parc de l'ancien hôpital militaire broussais, aujourd'hui occupé par des logements hlm. il comporte de très beaux arbres (sequoiadendron, arbousier)",17,"parks",17);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.227600,-1.509340,"Boulevard auguste peneau",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc du grand-blottereau","Le parc du grand-blottereau a été légué à la ville par larmateur thomas dobrée. le château du 18ème siècle, uvre de larchitecte ceyneray, est décoré sur sa façade par des massifs de broderies à la française utilisant des motifs décoratifs classiques.",18,"parks",18);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.243100,-1.522930,"Rue augustin fresnel",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square augustin fresnel","Petit espace de verdure entre la rue louis guiotton et la rue auguste fresnel",19,"parks",19);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.245000,-1.524710,"Boulevard de la pilotière - boulevard jules verne",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square pilotière","",20,"parks",20);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.245200,-1.524040,"Boulevard jules verne",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Centre social de la pilotière","Square de quartier avec jeux pour enfants et plantations",21,"parks",21);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.235500,-1.525410,"Avenue jacques auneau - rue des clématites",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc potager croissant","",22,"parks",22);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.190900,-1.530780,"Avenue des palmiers",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc potager de la crapaudine","En 1998, un groupe dune douzaine de personnes fonde une association afin de réaliser un projet de jardins familiaux et de jardin pédagogique sur une réserve foncière de la ville située entre saint jacques et sèvres : lassociation des jardins de la crapa",23,"parks",23);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.196900,-1.544800,"Rue dos d'ane",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Jardin confluent","",24,"parks",24);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.182900,-1.519650,"Avenue camille guerin",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square du vieux parc de sèvre","Le square du vieux parc de sèvre était à l'origine le parc d'une maternité.exceptionnellement en période de crue importante de la sèvre, une partie du parc peut héberger les vaches écossaises vivantt habituellement sur les prés de sèvre.",25,"parks",25);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.201100,-1.580720,"Rue des garennes",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square maurice schwob","Implanté au-dessus d'un front rocheux important, ce square dessiné par coutant au début du siècle domine la loire et propose de fait, un point de vue intéressant sur le fleuve.en 1932, etienne coutan envisage une promenade en corniche reliant les hauteu",26,"parks",26);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.200800,-1.593070,"Rue des courtils",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square des courtils","Le square des courtils est situé au cur du quartier chantenay. ce site aménagé en 1989 se compose de petites placettes, d'un terrain central actuellement sablé, d'une piste de skate et d'une aire de jeu clôturée pour les enfants de 2 à 7 ans. apprécié de",27,"parks",27);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.204200,-1.592940,"Rue maurice terrien",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square jean le gigant","Espace vert de quartier, ce square équipé d'une pataugeoire et d'un espace de jeux,  fait le bonheur des enfants aux beaux jours.",28,"parks",28);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.201500,-1.598010,"Rue de l'abbaye - chemin de la petite boucardière",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc de la boucardiere","Aménagée sommairement, cette ancienne propriété privée est un espace vert de quartier pour la ballade et les jeux d'enfants.",29,"parks",29);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.202700,-1.608340,"Rue charles housset",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square charles housset","Situé au milieu d'un carrefour, ce square est avant tout un espace vert d'accompagnement de voirie.",30,"parks",30);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.195000,-1.615590,"Rue des usines",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square toussaint louverture","La réalisation de ce square est récente. un belvédère ouvre la vue sur la loire et ses installations portuaires. les végétaux sont à dominante méditerranéenne.",31,"parks",31);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.204900,-1.610280,"Rue etienne coutan",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square du bois de la musse","Espace  de transition piétonne, cet espace vert est planté de vieux arbres qui lui donnent un caractère naturel au coeur d'une cité d'habitat social.",32,"parks",32);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.207800,-1.592020,"Rue du bois hercé - rue de la marseillaise",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square de la marseillaise","Espace de transition inter quartier, ce square ouvert est équipé d'un espace de jeux pour petits.",33,"parks",33);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.202200,-1.577320,"Rue de l'hermitage",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square marcel moisan","'Situé à proximité du planétarium, ce square réhabilité en 1995 présente un cadran solaire ''le scaphé de bérose'' et des plantes sélectionnées dans la littérature de jules verne.'",34,"parks",34);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.208100,-1.609830,"Rue francis portais - rue de l'adour",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square des marthyrs irlandais","Situé dans l'emprise d'une zac, ce square fera prochainement l'objet d'une recomposition complète.",35,"parks",35);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.224800,-1.594120,"Rue louis le nain",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc des dervallières","",36,"parks",36);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.212200,-1.587080,"Rue du prinquiau - boulevard de l'egalité",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square du prinquiau","Petit espace vert de quartier, ce square va être inscrit dans un programme de réhabilitation pour les années à venir.",37,"parks",37);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.214400,-1.574440,"Place canclaux",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square canclaux","Ce square est en cours de restauration. situé au centre d'un immense giratoire, il assure à la fois des fonctions d'espace public classique et d'espace vert avec également des jeux pour petits.",38,"parks",38);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.209300,-1.570750,"Rue mathurin brissoneau - place rené bouhier",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square des combattants d'afrique du nord","Restauré en 1995, cet espace offre au quartier un espace de jeux pour jeunes enfants.",39,"parks",39);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.212500,-1.590510,"Rue jules piedeleu",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc potager fournillère","",40,"parks",40);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.207800,-1.580380,"Rue de pilleux - rue benoit frachon",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square zac pilleux nord","",41,"parks",41);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.219200,-1.563820,"Place edouard normand",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square etienne destranges","",42,"parks",42);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.225300,-1.562760,"Rue noire",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc des capucins","Ce parc d'une superficie de 8500 m² a ouvert ses porte le 13 février 1993. son entrée principale donne sur la rue noire et il vient ainsi desservir un quartier fortement urbanisé, peu favorisé en espaces verts.cette propriété et ses batiments ont été co",43,"parks",43);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.224300,-1.581560,"Rue des dervallières, boulevard des anglais",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc de proce","Le parc a été créé au milieu du siècle dernier, d'après les plans de d. noisette, autour d'un manoir datant de 1789.le parc a été progressivement restauré et enrichi de collections diverses telles que les rhododendrons, magnolias, fuchsias, dahlias et b",44,"parks",44);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.222100,-1.551880,"Quai ceineray",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square maquis de saffré","Les abords de l'entrée du tunnel de détournement de l'erdre ont été aménagés dans les années 1930. l'actuel square du maquis de saffré, en prolongement du cours saint andré, fait face aux tables mémoriales de la guerre de 1914 1918. le jardin commence mêm",45,"parks",45);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.222200,-1.581530,"Rue des dervallières",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Jardin d'enfants de procé","",46,"parks",46);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.226000,-1.554380,"Quai de versailles",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square ile de versailles","L'ile a été réalisée avec des matériaux de dragage lors du creusement du canal de nantes à brest puis a été occupée par des activités artisanales diverses liées à la rivière.c'est à partir de 86, après que la ville ait terminé l'acquisition des dernière",47,"parks",47);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.231100,-1.553320,"Rue toulmouche - rue félix thomas",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square félix thomas","",48,"parks",48);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.228800,-1.566010,"Place emile fritsch",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square saint pasquier","",49,"parks",49);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.216400,-1.524070,"Rue de hongrie - rue de chypre",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square hongrie","",50,"parks",50);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.227700,-1.526750,"Boulevard ernest dalby",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc de la noe mitrie","Un des jardins les mieux appréciés des enfants : deux grandes pataugeoires, de grandes aires de jeux, un bel espace arboré avec de très beaux arbres, cyprès chauve de louisianne et plantes de terre de bruyère.",51,"parks",51);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.222600,-1.527530,"Rue jean-baptiste barre",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square jean-baptiste barre","Ce petit square situé dans le quartier toutes aides a été entièrement rénové en 1995, on y trouve une fontaine à l'italienne ornée d'un mascaron et d'une petite aire de jeux.",52,"parks",52);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.225400,-1.522590,"Rue jules brechoir",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square jules bréchoir","Petit jardin de proximité dans les anciens bains douche de toutes aides,",53,"parks",53);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.218200,-1.517960,"Boulevard de sarrebruck",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc de malakoff","Même s'il n'a pas le prestige des grands parcs nantais, c'est pour les habitants de la cité de malakoff un formidable poumon vert. dénommé également parc de mauves, il a été créé au début des années 1980 sur la décharge municipale occupant une partie de l",54,"parks",54);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.214900,-1.536880,"Mail pablo picasso",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc pablo picasso","",55,"parks",55);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.218300,-1.545130,"Rue saint francois",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square saint françois","Petit square de proximité avec jeux dans le quartier richebourg.",56,"parks",56);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.221554,-1.533176,"Rue francisco ferrer",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc de la moutonnerie","Le parc de la moutonnerie a été ouvert en 1997, aménagé sur le thème des jeux de société, on y trouve une aire de jeux pour enfants, un espace sportif de proximité, une dizaine de jardins familiaux et un vaste espace gazonné.",57,"parks",57);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.208100,-1.525210,"Place basse mar",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Place basse mar","Situé à la pointe est de l'île beaulieu, ce jardin est destiné aux jeunes enfants avec sa pataugeoire.",58,"parks",58);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.203900,-1.536090,"Boulevard general degaule",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square marcel launay","Espace vert de promenade et de liaison à proximité du grand centre commercial de l'ile de nantes",59,"parks",59);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.211400,-1.520530,"Cours de la prairie d'amont",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc de beaulieu","Grand espace naturel situé à la pointe de l'ile de nantes, ce parc bénéficie d'une situation particulière entre les deux bras de la loire.",60,"parks",60);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.203800,-1.547950,"Place wattignies - rue de l'echappée - rue petite biesse",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Place wattignies","",61,"parks",61);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.205300,-1.531530,"Rue jules sebilleau",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square rue jules sebilleau","Cet espace va être prochainement réaménagé en espace sportif et en espaces de jeux pour enfants.",62,"parks",62);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.202300,-1.551380,"Rue du scorff",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square benoni goulin","",63,"parks",63);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.205700,-1.544890,"Rue louis joxe - allée des hélices - rue de récife",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Le jardin des fonderies","Le jardin des fonderies a été aménagé sous la halle métallique des anciennes fonderies de l'atlantique. au cours de sa réhabilitation, elle a été recouverte d'une toiture translucide assurant un micro-climat favorable à la végétation luxuriante et exotiqu",64,"parks",64);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.205200,-1.549960,"Boulevard gustave roch",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square gustave roch","Petit square situé sur l'ile sainte anne, doté de quelques jeux pour enfants et d'un espace de jeu de ballon.",65,"parks",65);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.207700,-1.559640,"Quai françois mitterrand",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Jardin mabon","Le respect de l'héritage historique de l'ile de nantes et la revalorisation de l'existant étaient les axes prioritaires du réaménagement entrepris par l'équipe chémétoff. c'est une friche de l'usine alstom où une végétation spontanée s'était développée su",66,"parks",66);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.202400,-1.546590,"Boulevard des martyrs nantais de la resistance",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square vertais","Situé sur l'ile beaulieu, ce square de quartier a été réhabilité en 2001, on y trouve ainsi une aire de jeux protégée, quelques équipements sportifs et un petit groupe de jardins familiaux. le viaduc sncf confié au grapheur boris briand accueille une jung",67,"parks",67);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.208600,-1.527400,"Place de la guirouee",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Place de la guirouée","Réalisé en 2000,en complément de la place basse mar, il accueille les petits en toute sécurité avec quelques jeux,",68,"parks",68);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.207500,-1.533670,"Rue celestin frenet ou rue gaetan rondeau",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Jardin des cinq sens","Le jardin des 5 sens est conçu comme un espace d'accueil. la sollicitation des 5 sens a été privilégiée à travers le tracé, les équipements et les plantations. la fontaine musicale et les jeux d'eau sollicitent l'ouïe, les arbres et arbustes à feuilles et",69,"parks",69);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.205900,-1.567150,"Boulevard léon bureau - boulevard de la prairie au",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Le parc des chantiers","Le parc des chantiers est situé à l'ouest de l'île de nantes, entre les nefs et le hangar à bananes. il a été  aménagé sur le site des anciens chantiers navals. en fait, ce sont plusieurs jardins qui constituent ce parc d'une surface de 13 ha :  jardin de",70,"parks",70);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.245200,-1.579520,"Carrefour patouillerie - robert schuman",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc de la gaudiniere","Le parc fut créé au 18ème siècle et racheté par la ville en 1936. il fut alors scindé en 3 parcelles, la première consacrée au cimetière, la seconde transformée en parc public et la troisième affectée à un centre de rééducation. ces amputations successive",71,"parks",71);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.230600,-1.585280,"Rue jacques feyder",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square louis feuillade","",72,"parks",72);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.235100,-1.571410,"Boulevard des américains",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square gaston michel","",73,"parks",73);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.238100,-1.582550,"Petite avenue de lonchamp",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Jardin des nectars","S'inspirant des anciens vergers du site, le jardin est structuré par les lignes d'arbres fruitiers en espaliers, elles se prolongent dans l'alignement des poiriers d'ornements sur la rue et sur l'allée de desserte de l'école,",74,"parks",74);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.263100,-1.570950,"Boulevard albert einstein",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc potager amande","",75,"parks",75);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.270900,-1.585380,"Rond-point jean moulin",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Cimetiere paysager","Il peut sembler étrange de conseiller un cimetière comme lieu de promenade, mais ce quinzième cimetière nantais présente des caractéristiques qui lui valent depuis sa création de nombreuses visites d'amateurs et de promeneurs.par son importance, le cime",76,"parks",76);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.257800,-1.559230,"Rues stéphane leduc - de la petite sensive - de rome - des renards - dorsay",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square des renards","",77,"parks",77);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.247600,-1.566880,"Boulevard des tribunes",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc du petit port","",78,"parks",78);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.254500,-1.570740,"Rue marcel proust - rue henri bergson",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Jeux de boules proust bergson","",79,"parks",79);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.266900,-1.521270,"Allee de portrick saint joseph de porterie",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Jardin des farfadets","Petit square de quartier situé à saint joseph de porterieune plantation régulière de pommiers fleurs isole une pelouse permettant les jeux de ballon au milieu du verger, des plantations de petits fruits forment des haies à l'ancienne.",80,"parks",80);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.245300,-1.541660,"Rue coetquelfen",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square belle ile","",81,"parks",81);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.266200,-1.523040,"Rue de la grange au loup",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square barbara","Dans sa chanson « nantes », la chanteuse barbara évoque la « rue de la grange au loup » où elle vient retrouver, trop tard, son père mourant. cette rue nexistait pas à lépoque, mais le père de barbara occupait bien dans le quartier de st joseph de porte",82,"parks",82);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.254400,-1.520010,"Rue leon serpollet",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Square de la halvèque","Plaine de jeux particulièrement attractive pour le quartier avec de nombreux jeux pour enfants et une pataugeoire bien intègrée dans les équipements publics (bibliothèque, centre social ....)",83,"parks",83);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.287500,-1.524460,"Route de gachet",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc de la chantrerie","Cette propriété est reliée au centre de la ville par une promenade pour piétons de 6 km sur la rive gauche de l'erdre. acquis en 1972, ce parc a comme procé été dessiné un siècle plus tôt par d. noisette. l'aménagement très paysager, constitué de bosquets",84,"parks",84);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.268900,-1.516770,"Rue tristan corbieres saint joseph de porterie",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Jardin du zenith","Petit square de quartier situé à saint joseph de porterie, entouré de pergolas de bois et de plantations de rosiers,",85,"parks",85);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.267000,-1.519000,"Rue du nadir saint joseph de porterie",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Jardin du nadir","Petit square de quartier situé à saint joseph de porterie avec des jeux pour enfants.",86,"parks",86);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.265900,-1.519740,"Rue de l'embellie saint joseph de porterie",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Jardin des quatre jeudis","Jardin situé à proximité du bourg de saint joseph de porterie. il a permis la conservation d'un petit bois lors de la création de la zac. des jeux d'enfants permettent une animation au coeur du quartier.",87,"parks",87);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.262900,-1.532420,"Route de saint joseph",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc de la beaujoire","Le parc de la beaujoire a été créé à l'occasion des floralies de 71. la fontaine monumentale, l'une des plus grandes d'europe, anime les manifestations.au nord, sur 12 ha, le parc floral est plus spécifiquement voué au paysage et à l'horticulture.le v",88,"parks",88);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.235000,-1.536080,"Rond point de paris rue de racapé",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Parc du plessis tison","Le parc du plessis tison est fréquenté par les habitants du quartier. il comporte une pataugeoire et des jeux d'enfants. on peut y trouver de nombreuses espèces de chênes. particularité de ce parc une montagne comparable bien que de moindre importance à c",89,"parks",89);
INSERT INTO `parks`(`games`) VALUES (0);
INSERT INTO `gps`(`longitude`, `latitude`, `address`, `zip`, `city`) VALUES (47.256900,-1.523010,"Route de saint joseph",44000,"Nantes");
INSERT INTO `points_of_interest`(`label`, `description`,`gps_id`, `type`, `type_id_in_table`) VALUES ("Abords du stade de la beaujoire","La création du stade de la beaujoire a permis de créer un parc rustique aux abords de cet équipement, très utilisé comme zone récréative pour les promeneurs du quartier de la halvêque.",90,"parks",90);
INSERT INTO `parks`(`games`) VALUES (0);
